arr=[int(x) for x in input().split()]
arr.sort()
i=0
j=len(arr)-1
diff=int(input())
while(i<j):
    if(arr[j]-arr[i]>diff):
        j=j-1
        if(j==i+1):
            j=len(arr)-1
            i=i+1
    elif(arr[j]-arr[i]<diff):
        j=len(arr)-1
        i=i+1
    else:
        print(i,j)
        if(arr[j]==arr[j-1]):
            j=j-1
        else:
            i=i+1
            j=len(arr)-1
